// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userv3.proto

package com.sharan.grpc;

public final class Userv3 {
  private Userv3() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014userv3.proto\032\nuser.proto2\231\002\n\004user\022$\n\005l" +
      "ogin\022\r.LoginRequest\032\014.APIResponse\022\036\n\006log" +
      "out\022\006.Empty\032\014.APIResponse\022O\n\032GreetManyTi" +
      "mesServerStream\022\026.GreetManyTimesRequest\032" +
      "\027.GreetManyTimesResponse0\001\0226\n\tLongGreet\022" +
      "\021.LongGreetRequest\032\022.LongGreetResponse\"\000" +
      "(\001\022B\n\rGreetEveryone\022\025.GreetEveryoneReque" +
      "st\032\026.GreetEveryoneResponse(\0010\001B\021\n\017com.sh" +
      "aran.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.sharan.grpc.User.getDescriptor(),
        }, assigner);
    com.sharan.grpc.User.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
